; PlatformIO Project Configuration File
; Module 1 - Electronics Basic
;
; To switch exercise: change default_envs below
; Then click Upload button

[platformio]
default_envs = ex01

[env:ex01]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex01_led_blink.cpp>
; Ex01: Basic LED ON/OFF - GPIO digital output, Bit = 0 or 1

[env:ex02]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex02_binary_counter.cpp>
; Ex02: Binary counter 0→15 on 4 LEDs - Decimal to Binary conversion

[env:ex03]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex03_ohms_law.cpp>
; Ex03: Ohm's law V=IR, Power W=VxI, ADC voltage reading

[env:ex04]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex04_memory_hex.cpp>
; Ex04: Memory table, Hexadecimal, ASCII display on Serial Monitor

[env:ex05]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex05_logic_gates.cpp>
; Ex05: Logic Gates AND/OR/NOT/NAND/XOR with buttons and LEDs

[env:ex06]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex06_hex_ascii.cpp>
; Ex06: Hex & ASCII interactive lesson with quiz

[env:ex07]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex07_adc_potentiometer.cpp>
; Ex07: ADC - Potentiometer controls LED brightness (PWM)

[env:ex07_b]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex07_b_HC-SR04.cpp>
; Ex07: ADC - HC-SR04 controls LED brightness (PWM)

[env:ex08]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_src_filter = +<ex08_adc_light_sensor.cpp>
; Ex08: ADC - LDR light sensor with threshold detection